<?php
include ("MSSQL.php");
$sql2 = "if not exists (select * from sysobjects where name='USER1' and xtype='U')CREATE TABLE SHEET1 (
RID INT IDENTITY(1,1) PRIMARY KEY, 
PART_NO VARCHAR(255) NOT NULL,
PARTI VARCHAR(255) NOT NULL,
MRP VARCHAR(255),
GROP VARCHAR(255),
CATE VARCHAR(255),
DPCODE VARCHAR(255),
lmodi VARCHAR(255),
TRATE VARCHAR(255),
RID1 VARCHAR(255),
UNIT VARCHAR(255),
AEDT VARCHAR(255)
)";

$sql1 = "if not exists (select * from sysobjects where name='USER1' and xtype='U')CREATE TABLE TABLE2 (
RID1 INT IDENTITY(1,1) PRIMARY KEY,
TYPE VARCHAR(255), 
PART_NO VARCHAR(255) NOT NULL,
PARTI VARCHAR(255) NOT NULL,
MRP VARCHAR(255),
QTY VARCHAR(255),
TOTAL VARCHAR(255),
RACKNO VARCHAR(255),
TAX VARCHAR(255),
TVAL VARCHAR(255),
STOTAL VARCHAR(255),
PPRICE VARCHAR(255),
SPRICE VARCHAR(255),
SSTA VARCHAR(255),
EOR VARCHAR(255),
GROP VARCHAR(255),
DPCODE VARCHAR(255),
lmodi VARCHAR(255),
RID VARCHAR(255),
UNIT VARCHAR(255),
AEDT VARCHAR(255),
USER1 VARCHAR(255)
)";
$sql = "if not exists (select * from sysobjects where name='USER1' and xtype='U') CREATE TABLE USER1 ("
      . " ID INT IDENTITY(1,1) PRIMARY KEY" 
      . ", UID VARCHAR(255) NOT NULL"
      . ", PASS VARCHAR(255)"
      . ", FNAME VARCHAR(255)"
      . ", LNAME VARCHAR(255)"
      . ")";
	  
$sql3 = "if not exists (select * from sysobjects where name='USER1' and xtype='U') CREATE TABLE MAINPOPUs(
	RID INT IDENTITY(1,1) PRIMARY KEY,
	RID1 NVARCHAR(max) NULL DEFAULT NULL,
	SID NVARCHAR(max) NULL DEFAULT NULL,
	CNAME NVARCHAR(max) NULL DEFAULT NULL,
	SNAME NVARCHAR(max) NULL DEFAULT NULL,
	ENS NVARCHAR(max) NULL DEFAULT NULL,
	ALSN NVARCHAR(max) NULL DEFAULT NULL,
	RAT_PH NVARCHAR(max) NULL DEFAULT NULL,
	PHASE NVARCHAR(max) NULL DEFAULT NULL,
	MODEL NVARCHAR(max) NULL DEFAULT NULL,
	BSN NVARCHAR(max) NULL DEFAULT NULL,
	CPN NVARCHAR(max) NULL DEFAULT NULL,
	PHNO NVARCHAR(max) NULL DEFAULT NULL,
	ADDR NVARCHAR(max) NULL DEFAULT NULL,
	DOC DATETIME NULL DEFAULT NULL,
	SPIN NVARCHAR(max) NULL DEFAULT NULL,
	AMC NVARCHAR(max) NULL DEFAULT NULL,
	CHMR NVARCHAR(max) NULL DEFAULT NULL,
	CHMD DATETIME NULL DEFAULT NULL,
	lhmr NVARCHAR(max) NULL DEFAULT NULL,
	lsd DATETIME NULL DEFAULT NULL,
	nsd DATETIME NULL DEFAULT NULL,
	ahm NVARCHAR(max) NULL DEFAULT NULL,
	DGNO NVARCHAR(max) NULL DEFAULT NULL,
	ACTION NVARCHAR(max) NULL DEFAULT NULL,
	DIST NVARCHAR(max) NULL DEFAULT NULL,
	STATE NVARCHAR(max) NULL DEFAULT NULL,
	AMAKE NVARCHAR(max) NULL DEFAULT NULL,
	WARR NVARCHAR(max) NULL DEFAULT NULL,
	OEA NVARCHAR(max) NULL DEFAULT NULL,
	SSTA NVARCHAR(max) NULL DEFAULT NULL,
	hmage NVARCHAR(max) NULL DEFAULT NULL,
	DPCODE NVARCHAR(max) NULL DEFAULT NULL,
	lmodi NVARCHAR(max) NULL DEFAULT NULL,
	AEDT NVARCHAR(max) NULL DEFAULT NULL,
	llop NVARCHAR(max) NULL DEFAULT NULL,
	solenoid NVARCHAR(max) NULL DEFAULT NULL,
	chalt NVARCHAR(max) NULL DEFAULT NULL,
	starter NVARCHAR(max) NULL DEFAULT NULL,
	cntype NVARCHAR(max) NULL DEFAULT NULL,
	cnmake NVARCHAR(max) NULL DEFAULT NULL,
	sauto NVARCHAR(max) NULL DEFAULT NULL,
	FRAME NVARCHAR(max) NULL DEFAULT NULL,
	DSTA NVARCHAR(max) NULL DEFAULT NULL
)"
;
$sql4 ="if not exists (select * from sysobjects where name='USER1' and xtype='U') CREATE TABLE PMRs (
	RECID1 INT IDENTITY(1,1) PRIMARY KEY,
	SID NVARCHAR(max) NULL DEFAULT NULL,
	SNAME NVARCHAR(max) NULL DEFAULT NULL,
	ENGINE_No NVARCHAR(max) NULL DEFAULT NULL,
	DOS DATETIME NULL DEFAULT NULL,
	STYPE NVARCHAR(max) NULL DEFAULT NULL,
	HMR NVARCHAR(max) NULL DEFAULT NULL,
	Report NVARCHAR(max) NULL DEFAULT NULL,
	Technician NVARCHAR(max) NULL DEFAULT NULL,
	METERIAL NVARCHAR(max) NULL DEFAULT NULL,
	CUST NVARCHAR(max) NULL DEFAULT NULL,
	recid NVARCHAR(max) NULL DEFAULT NULL,
	CDATI DATETIME NULL DEFAULT NULL,
	DIST NVARCHAR(max) NULL DEFAULT NULL,
	STATE NVARCHAR(max) NULL DEFAULT NULL,
	CCATE NVARCHAR(max) NULL DEFAULT NULL,
	MODEL NVARCHAR(max) NULL DEFAULT NULL,
	DOI DATETIME NULL DEFAULT NULL,
	DGNO NVARCHAR(max) NULL DEFAULT NULL,
	AMAKE NVARCHAR(max) NULL DEFAULT NULL,
	ALSN NVARCHAR(max) NULL DEFAULT NULL,
	BSN NVARCHAR(max) NULL DEFAULT NULL,
	CNAT NVARCHAR(max) NULL DEFAULT NULL,
	SERV NVARCHAR(max) NULL DEFAULT NULL,
	RFAIL NVARCHAR(max) NULL DEFAULT NULL,
	STA NVARCHAR(max) NULL DEFAULT NULL,
	WARR NVARCHAR(max) NULL DEFAULT NULL,
	ACTION NVARCHAR(max) NULL DEFAULT NULL,
	OEA NVARCHAR(max) NULL DEFAULT NULL,
	AMC NVARCHAR(max) NULL DEFAULT NULL,
	TTR NVARCHAR(max) NULL DEFAULT NULL,
	SLA NVARCHAR(max) NULL DEFAULT NULL,
	TSLOT NVARCHAR(max) NULL DEFAULT NULL,
	RESLA NVARCHAR(max) NULL DEFAULT NULL,
	KVA NVARCHAR(max) NULL DEFAULT NULL,
	SSTA NVARCHAR(max) NULL DEFAULT NULL,
	DPCODE NVARCHAR(max) NULL DEFAULT NULL,
	lmodi NVARCHAR(max) NULL DEFAULT NULL,
	AEDT NVARCHAR(max) NULL DEFAULT NULL,
	REM NVARCHAR(max) NULL DEFAULT NULL
)
";
$query = sqlsrv_query($conn, $sql);
	  if( $query === false ) {
     die( print_r( sqlsrv_errors(), true));
}

$query = sqlsrv_query($conn, $sql1);
	  if( $query === false ) {
     die( print_r( sqlsrv_errors(), true));
}

$query = sqlsrv_query($conn, $sql2);
	  if( $query === false ) {
     die( print_r( sqlsrv_errors(), true));
}
$query = sqlsrv_query($conn, $sql3);
	  if( $query === false ) {
     die( print_r( sqlsrv_errors(), true));
}

$query = sqlsrv_query($conn, $sql4);
	  if( $query === false ) {
     die( print_r( sqlsrv_errors(), true));
}
?>